repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files


- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      exclude: migrations
      args: [--profile, black, --line-length=79]


- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      args: [--max-line-length=79]
      exclude: (migrations|config/settings)


- repo: https://github.com/ambv/black
  rev: 23.3.0
  hooks:
    - id: black
      exclude: (migrations|config/settings/)
      args: [ --line-length=79]
