version: '3'
# change DB_HOST to "localhost" in .env

services:
  postgres:
    container_name: postgres_local_container
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

volumes:
  postgres-data:
