from telegram.ext import ConversationHandler

POSITION_RESULT = 'POSITION_RESULT'
POSITION_SUBSCRIBE = 'POSITION_SUBSCRIBE'
RATE_RESULT = 'RATE_RESULT'
STOCK_RESULT = 'STOCK_RESULT'
END = ConversationHandler.END
