# Generated by Django 4.2.2 on 2023-07-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время добавления')),
                ('articul', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время добавления')),
                ('warehouse_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время добавления')),
                ('articul', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время добавления')),
                ('user_id', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
